[build]
  base = "."
  command = "npm install && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22.13.1"
  NEXT_PUBLIC_CONTENTFUL_SPACE_ID = "your_space_id"
  NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN = "your_access_token"
  NEXT_PUBLIC_CONTENTFUL_PREVIEW_ACCESS_TOKEN = "your_preview_token"
  CONTENTFUL_PREVIEW_SECRET = "your_preview_secret"
  CONTENTFUL_REVALIDATE_SECRET = "your_revalidate_secret"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["node_modules/**/*"] 